name: letterdude
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  split_view: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  fonts:
    - family: gg sans
      fonts:
        - asset: assets/fonts/gg-sans/gg-sans-Regular.ttf
          weight: 400
        - asset: assets/fonts/gg-sans/gg-sans-Medium.ttf
          weight: 500
        - asset: assets/fonts/gg-sans/gg-sans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gg-sans/gg-sans-Bold.ttf
          weight: 700
