name: letterdude
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  get_it: ^7.6.4
  logger: ^2.0.2+1
  path: ^1.8.3
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  split_view: ^3.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: gg sans
      fonts:
        - asset: assets/fonts/gg-sans/gg-sans-Regular.ttf
          weight: 400
        - asset: assets/fonts/gg-sans/gg-sans-Medium.ttf
          weight: 500
        - asset: assets/fonts/gg-sans/gg-sans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gg-sans/gg-sans-Bold.ttf
          weight: 700
